### ISSUE TITLE
Frontend background is white instead of gray

### ISSUE THREAD

**Issue by gameuser1982** [AlmostEfficient/full-stack-solana-dev#4]
So I'm really terrible at frontend type work and I'm trying to improve that. I find backend type work easier and the Rust side of things were pretty smooth.

Unlike the tutorial video that Mr Raza @AlmostEfficient made, my frontend background is white with black text.

![Screenshot (1939)](https://github.com/AlmostEfficient/full-stack-solana-dev/assets/59629681/cefa003e-5ddf-4e8d-aa04-f735f48b343c)

But this is how it looks on Mr Raza's tutorial video:

![Screenshot (1940)](https://github.com/AlmostEfficient/full-stack-solana-dev/assets/59629681/00a3439d-987d-4a4f-a3b2-4c54ed8ad9c7)

Did I miss a CSS file somewhere or is Mr Raza running some sort of universal dark mode on his browser? My frontend functions exactly the same otherwise and can interact with the on chain Solana program 🎉

**Comment by AlmostEfficient** [comment]
lol I DO have a universal dark mode browser extension but it's likely I just forgot to mention the style updates. 

Compare this to yours: https://github.com/AlmostEfficient/full-stack-solana-dev/blob/main/front-end/src/index.css
